CMS-Web/Areas/Admin/Controllers/CMSCategoriesController.cs
using CMS_DTO.CMSCategories;
using CMS_Shared;
using CMS_Shared.CMSCategories;
using CMS_Shared.Utilities;
using CMS_Web.Areas.Admin.Models.Categories;
using CMS_Web.Web.App_Start;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CMS_Web.Areas.Admin.Controllers
{
    [NuAuth]
    public class CMSCategoriesController : HQController
    {
        private CMSCategoriesFactory _factory;
        public CMSCategoriesController()
        {
            _factory = new CMSCategoriesFactory();
            ViewBag.Category = GetListCategorySelectItem();
        }
        // GET: Admin/CMSCategories
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadGrid()
        {
            var model = _factory.GetList();
            model.ForEach(x =>
            {
                x.sStatus = x.IsActive ? "Kích hoạt" : "Chưa kích hoạt";
                if (!string.IsNullOrEmpty(x.ImageURL))
                    x.ImageURL = Commons.HostImage + "Categories/" + x.ImageURL;
            });
            return PartialView("_ListData",model);
        }

        public ActionResult Create()
        {
            CMSCategoriesModels model = new CMSCategoriesModels();
            return PartialView("_Create", model);
        }

        public CMSCategoriesModels GetDetail(string Id)
        {
            return _factory.GetDetail(Id);
        }

        [HttpPost]
        public ActionResult Create(CMSCategoriesModels model)
        {
            try
            {
                byte[] photoByte = null;

                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Create", model);
                }
                if (model.PictureUpload != null && model.PictureUpload.ContentLength > 0)
                {
                    Byte[] imgByte = new Byte[model.PictureUpload.ContentLength];
                    model.PictureUpload.InputStream.Read(imgByte, 0, model.PictureUpload.ContentLength);
                    model.PictureByte = imgByte;
                    model.ImageURL = Guid.NewGuid() + Path.GetExtension(model.PictureUpload.FileName);
                    model.PictureUpload = null;
                    photoByte = imgByte;
                }
                var Id = "";
                var msg = "";
                var result = _factory.CreateOrUpdate(model,ref Id,ref msg);
                if (result)
                {
                    if (!string.IsNullOrEmpty(model.ImageURL) && model.PictureByte != null)
                    {
                        var path = Server.MapPath("~/Uploads/Categories/" + model.ImageURL);
                        MemoryStream ms = new MemoryStream(photoByte, 0, photoByte.Length);
                        ms.Write(photoByte, 0, photoByte.Length);
                        System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);

                        ImageHelper.Me.SaveCroppedImage(imageTmp, path, model.ImageURL, ref photoByte, Commons.WidthCate, Commons.WidthCate, Commons.HeightCate);
                    }
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("CategoryCode", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Create", model);
            }
            catch(Exception ex) {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Create", model);
            }
        }

        [HttpGet]
        public ActionResult Edit(string Id)
        {
            var model = GetDetail(Id);
            if (!string.IsNullOrEmpty(model.ImageURL))
                model.ImageURL = Commons.HostImage + "Categories/" + model.ImageURL;
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(CMSCategoriesModels model)
        {
            var temp = model.ImageURL;
            try
            {
                byte[] photoByte = null;
                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Edit", model);
                }
                if (!string.IsNullOrEmpty(model.ImageURL))
                {
                    model.ImageURL = model.ImageURL.Replace(Commons._PublicImages, "").Replace("Categories/", "").Replace(Commons.Image200_100, "");
                    temp = model.ImageURL;
                }

                if (model.PictureUpload != null && model.PictureUpload.ContentLength > 0)
                {
                    Byte[] imgByte = new Byte[model.PictureUpload.ContentLength];
                    model.PictureUpload.InputStream.Read(imgByte, 0, model.PictureUpload.ContentLength);
                    model.PictureByte = imgByte;
                    model.ImageURL = Guid.NewGuid() + Path.GetExtension(model.PictureUpload.FileName);
                    model.PictureUpload = null;
                    photoByte = imgByte;
                }
                var Id = "";
                var msg = "";
                var result = _factory.CreateOrUpdate(model, ref Id, ref msg);
                if (result)
                {
                    if (!string.IsNullOrEmpty(model.ImageURL) && model.PictureByte != null)
                    {
                        if (System.IO.File.Exists(Server.MapPath("~/Uploads/Categories/" + temp)))
                        {
                            ImageHelper.Me.TryDeleteImageUpdated(Server.MapPath("~/Uploads/Categories/" + temp));
                        }

                        var path = Server.MapPath("~/Uploads/Categories/" + model.ImageURL);
                        MemoryStream ms = new MemoryStream(photoByte, 0, photoByte.Length);
                        ms.Write(photoByte, 0, photoByte.Length);
                        System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);

                        ImageHelper.Me.SaveCroppedImage(imageTmp, path, model.ImageURL, ref photoByte, Commons.WidthCate, Commons.WidthCate, Commons.HeightCate);
                    }
                    return RedirectToAction("Index");
                }                    
                ModelState.AddModelError("CategoryCode", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Edit", model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Edit", model);
            }
        }

        [HttpGet]
        public ActionResult View(string Id)
        {
            var model = GetDetail(Id);
            if (!string.IsNullOrEmpty(model.ImageURL))
                model.ImageURL = Commons.HostImage + "Categories/" + model.ImageURL;
            return PartialView("_View", model);
        }

        [HttpGet]
        public ActionResult Delete(string Id)
        {
            var model = GetDetail(Id);
            return PartialView("_Delete", model);
        }

        [HttpPost]
        public ActionResult Delete(CMSCategoriesModels model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Delete", model);
                }
                var msg = "";
                var result = _factory.Delete(model.Id, ref msg);
                if (result)
                {
                    if (System.IO.File.Exists(Server.MapPath("~/Uploads/Categories/" + model.ImageURL)))
                    {
                        ImageHelper.Me.TryDeleteImageUpdated(Server.MapPath("~/Uploads/Categories/" + model.ImageURL));
                    }

                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("CategoryName", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Delete", model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Delete", model);
            }
        }
    }
}

CMS-Web/Areas/Admin/Views/CMSCategories/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Thể loại - Danh sách";
}
<div role="main">
    <div class="se-pre-con" style="display: none;"></div>
    <div class="_gridview">
        <div class="page-title">
            <!-- BEGIN PAGE BAR -->
            @Html.Partial("_breadcrumb", new Dictionary<string, string> { { "A", "Trang chủ" }, { "B", "Thể loại - Danh sách" } })
            <!-- END PAGE BAR -->
        </div>
        <div class="page-main">
            @using (Html.BeginForm("LoadGrid", "CMSCategories", FormMethod.Post, new { @class = "form-horizontal search-form" }))
            {
            }
            @*<div class="gridview" style="height:100%;"></div>*@
        </div>      
    </div>
    <div class="detail-view" style="height:100%;">
        <!-- detail partial view -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        LoadGrid();
        $('input.icheck').iCheck({
            checkboxClass: 'icheckbox_square-grey',
            radioClass: 'iradio_square-green'
        });
    })

</script>

CMS-Web/Areas/Admin/Views/CMSCategories/_Create.cshtml
@model CMS_DTO.CMSCategories.CMSCategoriesModels
<div role="main" style="display:inline-block;height:100%;width:100%">
    @*<div class="se-pre-con" style="display: none;"></div>*@
    <div class="page-title">
        <!-- BEGIN PAGE BAR -->
        @Html.Partial("_breadcrumb", new Dictionary<string, string> { { "A", "Trang chủ" }, { "B", "Thể loại - Thêm mới" } })
        <!-- END PAGE BAR -->
    </div>
    <div class="page-main">
        <div class="col-md-12 col-sm-12 col-xs-12 x_panel">
            <div class="x_content">
                <div class="row text-right">
                    <ul class="header-buttons pull-right list-inline">
                        <li>
                            <a href="javascript:void(0)" class="btn btn-danger" id="btn-delete" onclick="CloseDetail()">
                                <i class="fa fa-times"></i>
                                &nbsp;Hủy
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="btn btn-success" id="btn-edit-save" onclick="SubmitForm('#form-create')">
                                <i class="fa fa-save"></i>
                                &nbsp;Lưu
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="box-body" style="display: block;">
                    @using (@Html.BeginForm("Create", "CMSCategories", FormMethod.Post, new { @id = "form-create", @class = "form-horizontal", @enctype = "multipart/form-data" }))
                    {
                        @Html.Partial("_Form", Model)
                    }
                </div>

            </div>
        </div>

    </div>
</div>
<script>
    $("#form-create").submit(function (e) {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
        $.ajax({
            url: $(this).attr('action'),
            type: "post",
            data: new FormData(this),
            processData: false,
            contentType: false,
            success: function () {
                CloseDetail();
                LoadGrid();
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $(".detail-view").html(jqXHR.responseText);
            }
        });
        e.preventDefault();
    });
</script>

CMS-Web/Areas/Admin/Views/CMSCategories/_Delete.cshtml
@model CMS_DTO.CMSCategories.CMSCategoriesModels
<div role="main" style="display:inline-block;height:100%;width:100%">
    @*<div class="se-pre-con" style="display: none;"></div>*@
    <div class="page-title">
        <!-- BEGIN PAGE BAR -->
        @Html.Partial("_breadcrumb", new Dictionary<string, string> { { "A", "Trang chủ" }, { "B", "Thể loại - Xóa" } })
        <!-- END PAGE BAR -->
    </div>
    <div class="page-main">
        <div class="col-md-12 col-sm-12 col-xs-12 x_panel">
            <div class="x_content">
                <div class="row text-right">
                    <ul class="header-buttons pull-right list-inline">
                        <li>
                            <a href="javascript:void(0)" class="btn btn-danger" id="btn-delete" onclick="CloseDetail()">
                                <i class="fa fa-times"></i>
                                &nbsp;Hủy
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="btn btn-success" id="btn-edit-save" onclick="SubmitForm('#form-delete')">
                                <i class="fa fa-save"></i>
                                &nbsp;Lưu
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="box-body" style="display: block;">
                    @using (@Html.BeginForm("Delete", "CMSCategories", FormMethod.Post, new { @id = "form-delete", @class = "form-horizontal", @enctype = "multipart/form-data" }))
                    {
                        <div class="form-group">
                            <label class="col-md-2 control-label"></label>
                            <div class="col-md-6" style="font-size: 20px; width: 100%;">
                                Bạn có chắc chắn muốn xóa <strong>[ @Model.CategoryName ]</strong>?
                                <br />
                                @Html.HiddenFor(model => model.Id)
                                @Html.HiddenFor(model => model.CategoryName)
                                @Html.HiddenFor(model => model.CategoryCode)
                                @Html.HiddenFor(model => model.ImageURL)
                                @Html.ValidationMessageFor(model => model.CategoryName, null, new { @class = "label" })
                            </div>
                        </div>
                    }
                </div>

            </div>
        </div>

    </div>
</div>

<script>
    $("#form-delete").submit(function (e) {
        $.ajax({
            beforeSend: function () {
                $('.se-pre-con').show();
            },
            url: $(this).attr('action'),
            type: "post",
            data: new FormData(this),
            processData: false,
            contentType: false,
            success: function () {
                CloseDetail();
                LoadGrid();
            },
            complete: function () {
                $('.se-pre-con').hide();
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $(".detail-view").html(jqXHR.responseText);
            }
        });
        e.preventDefault();
    });
</script>

CMS-Web/Areas/Admin/Views/CMSCategories/_Edit.cshtml
@model CMS_DTO.CMSCategories.CMSCategoriesModels
<div role="main" style="display:inline-block;height:100%;width:100%">
    @*<div class="se-pre-con" style="display: none;"></div>*@
    <div class="page-title">
        <!-- BEGIN PAGE BAR -->
        @Html.Partial("_breadcrumb", new Dictionary<string, string> { { "A", "Trang chủ" }, { "B", "Thể loại - Sửa" } })
        <!-- END PAGE BAR -->
    </div>
    <div class="page-main">
        <div class="col-md-12 col-sm-12 col-xs-12 x_panel">
            <div class="x_content">
                <div class="row text-right">
                    <ul class="header-buttons pull-right list-inline">
                        <li>
                            <a href="javascript:void(0)" class="btn btn-danger" id="btn-delete" onclick="CloseDetail()">
                                <i class="fa fa-times"></i>
                                &nbsp;Hủy
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="btn btn-success" id="btn-edit-save" onclick="SubmitForm('#form-edit')">
                                <i class="fa fa-save"></i>
                                &nbsp;Lưu
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="box-body" style="display: block;">
                    @using (@Html.BeginForm("Edit", "CMSCategories", FormMethod.Post, new { @id = "form-edit", @class = "form-horizontal", @enctype = "multipart/form-data" }))
                    {
                        @Html.Partial("_Form", Model)
                    }
                </div>

            </div>
        </div>

    </div>
</div>
<script>
    $("#form-edit").submit(function (e) {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
        $.ajax({
            beforeSend: function () {
                $('.se-pre-con').show();
            },
            url: $(this).attr('action'),
            type: "post",
            data: new FormData(this),
            processData: false,
            contentType: false,
            success: function () {
                CloseDetail();
                LoadGrid();
            },
            complete: function () {
                $('.se-pre-con').hide();
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $(".detail-view").html(jqXHR.responseText);
            }
        });
        e.preventDefault();
    });
</script>

CMS-Web/Areas/Admin/Views/CMSCategories/_Form.cshtml
@model CMS_DTO.CMSCategories.CMSCategoriesModels
@using CMS_Shared
@{
    Html.EnableUnobtrusiveJavaScript(true);
    var _ID = Model.Id;
}
@Html.HiddenFor(model =>model.Id)
@Html.HiddenFor(model => model.ImageURL)

<div class="row form-horizontal form-label-left" style="margin-bottom:15px;">
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12 lineHeight fontLighter">Hình ảnh</label>
        <div class="col-md-2 col-sm-2 col-xs-12">
            @if (!string.IsNullOrEmpty(Model.ImageURL))
            {
                <img id="upload-preview" src="@Model.ImageURL" height="100" width="100" class="" style="border-radius:100% !important" />
            }
            else
            {
                <img id="upload-preview" class="" src="@Commons.Image200_100" height="100" width="100" style="border-radius:100% !important" />
            }
        </div>
        <div class="col-md-1 col-sm-3 col-xs-12" style="line-height:55px;">
            <div class="upload-btn-wrapper" style="cursor:pointer;">
                <button class="btn btn-default" type="button" onclick="showPictureUpload();" style="margin-top:-6%;margin-left:50px">Chọn hình</button>
                @Html.TextBoxFor(model => model.PictureUpload, new { @type = "file", @onchange = "PreviewImage(this,\"upload-preview\")", @accept = "*.jpg", @class = "hidden", @id = "urlImage" })
            </div>
            @Html.ValidationMessageFor(model => model.PictureUpload, null, new { @class = "label label-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12 fontLighter">Mã thể loại</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.TextBoxFor(model => model.CategoryCode, new { @class = "form-control", @placeholder = "Mã thể loại", @autocomplete = "off" })
            @Html.ValidationMessageFor(model => model.CategoryCode, null, new { @class = "label label-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12 lineHeight fontLighter">Tên thể loại</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.TextBoxFor(model => model.CategoryName, new { @class = "form-control", @placeholder = "Tên thể loại", @autocomplete = "off" })
            @Html.ValidationMessageFor(model => model.CategoryName, null, new { @class = "label label-danger" })
        </div>
    </div>

    @*<div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12 lineHeight fontLighter">Thể loại cha</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.DropDownListFor(model => model.ParentId,
                new SelectList(ViewBag.Category, "Value", "Text", Model.ParentId),
                new
                {
                    @class = "form-control select2_multiple",
                    @id = "CategoryDdl",
                    @style = "width:100%;"
                })
                @Html.ValidationMessageFor(model => model.ParentId, null, new { @class = "label label-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12 fontLighter">Trạng thái</label>
        <div class="col-md-1 col-sm-1 col-xs-12">
            <label>@Html.CheckBoxFor(model => model.IsActive, new { @class = "icheck" })</label>
        </div>
    </div>

    <!--Description-->
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12 fontLighter">Mô tả</label>
        <div class="col-md-9 col-sm-9 col-xs-12">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control ckeditor", placeholder = "Mô tả" })
            @Html.ValidationMessageFor(model => model.Description, null, new { @class = "label" })
        </div>
    </div>
</div>
<script src="@Url.Content("~/Scripts/InputCustom.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#CategoryDdl").select2({
            placeholder: "Làm ơn chọn thể loại",
            //allowClear: true
        });
    })
    function showPictureUpload() {
        $('[id=urlImage]').click();
    }
</script>

CMS-Web/Areas/Admin/Views/CMSCategories/_ListData.cshtml
@{
    Layout = null;
}
@model List<CMS_DTO.CMSCategories.CMSCategoriesModels>
@*<style type="text/css">
    #sample_3 ul {
        width: 100% !important;
    }

        #sample_3 ul li .dtr-title {
            width: 25% !important;
        }

        #sample_3 ul li .dtr-data {
            width: 75% !important;
        }
</style>*@
<div class="table-responsive">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>Thể loại
                </div>
                <div class="actions">
                    <a href="javascript:;" class="btn btn-default btn-sm" onclick='ShowView("@Url.Action("Create","CMSCategories")")'>
                        <i class="fa fa-plus"></i> Thêm mới
                    </a>
                    @*<a href="javascript:;" class="btn btn-default btn-sm">
                        <i class="fa fa-print"></i> Print
                    </a>*@
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover dt-responsive" id="sample_3">
                    <thead>
                        <tr>
                            <th class="text-center">
                              Mã thể loại
                            </th>
                            <th class="text-center"> Tên thể loại </th>
                            <th class="text-center"> Số sản phẩm </th>
                            <th class="text-center"> Trạng thái </th>
                            <th class="text-center"> Tùy chỉnh </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td class="text-center">
                                        @item.CategoryCode
                                    </td>
                                    <td> @item.CategoryName </td>
                                    <td class="text-center">
                                        @item.NumberOfProduct
                                    </td>
                                    <td class="text-center">
                                        <span class="label label-sm label-success"> @item.sStatus </span>
                                    </td>
                                    <td class="text-center">
                                        <a href="javascript:void(0)"
                                           onclick='ShowView("@Url.Action("View","CMSCategories",new { Id=item.Id})")'
                                           class="btn btn-primary btn-xs view details"><i class="fa fa-eye"></i>&nbsp;Xem</a>&nbsp;&nbsp;
                                        <a href="javascript:void(0)"
                                           onclick='ShowView("@Url.Action("Edit","CMSCategories",new { Id=item.Id})")'
                                           class="btn btn-info btn-xs edit details"><i class="fa fa-edit"></i>&nbsp;Cập nhập</a>&nbsp;&nbsp;
                                        <a href="javascript:void(0)"
                                           onclick='ShowView("@Url.Action("Delete","CMSCategories",new { Id=item.Id})")'
                                           class="btn btn-danger btn-xs delete details"><i class="fa fa-trash-o"></i>&nbsp;Xóa</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>

<script type="text/javascript">
    var _tableCategory = null;
    var _settingsOptionTableCategory = {
        "language": {
            "aria": {
                "sortAscending": ": activate to sort column ascending",
                "sortDescending": ": activate to sort column descending"
            },
            "emptyTable": "No data available in table",
            "info": "Showing _START_ to _END_ of _TOTAL_ records",
            "infoEmpty": "No records found",
            "infoFiltered": "(filtered1 from _MAX_ total records)",
            "lengthMenu": "Show _MENU_",
            "search": "Search:",
            "zeroRecords": "No matching records found",
            "paginate": {
                "previous": "Prev",
                "next": "Next",
                "last": "Last",
                "first": "First"
            }
        },
        "oLanguage": {

            "sSearch": "Tìm Kiếm:",
            "sLengthMenu": "Xem _MENU_",
            "sProcessing": "Đang xử lý...",
            "sZeroRecords": "Không tìm thấy dòng nào phù hợp",
            "sInfo": "Đang xem _START_ đến _END_ trong tổng số _TOTAL_ mục",
            "sInfoEmpty": "Đang xem 0 đến 0 trong tổng số 0 mục",
            "sInfoFiltered": "(được lọc từ _MAX_ mục)",
            "sInfoPostFix": "",
        },
        "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

        "lengthMenu": [
            [6, 15, 20, -1],
            [6, 15, 20, "All"] // change per page values here
        ],
        // set the initial value
        "pageLength": 6,
        "columnDefs": [
            { "orderable": false, "targets": [0, 4] },
            { "width": "3%", "targets": [0] },
            { "width": "8%", "targets": [1] },
            { "width": "5%", "targets": [4] },
            { "width": "3%", "targets": [2, 3] },
        ],
        //"responsive": true,
        //"autoWitdh": false,
        "order": [
            [1, "asc"]
        ] // set first column as a default sort by asc
    };

    $(document).ready(function () {
        _tableCategory = $('#sample_3').DataTable($.extend(true, {}, _settingsOptionTableCategory));
       
    })
    function ShowView(url)
    {
        ShowViewOrEdit(url);
    }
</script>