CMS-Web/Areas/Admin/Controllers/CMSNewsController.cs
using CMS_DTO.CMSNews;
using CMS_Shared;
using CMS_Shared.CMSNews;
using CMS_Shared.Utilities;
using CMS_Web.Web.App_Start;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CMS_Web.Areas.Admin.Controllers
{
    [NuAuth]
    public class CMSNewsController : Controller
    {
        private CMSNewsFactory _factory;
        public CMSNewsController()
        {
            _factory = new CMSNewsFactory();
        }
        // GET: Admin/CMSCategories
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadGrid()
        {
            var model = _factory.GetList();
            model.ForEach(x =>
            {
                x.sStatus = x.IsActive ? "Kích hoạt" : "Chưa kích hoạt";
                if (!string.IsNullOrEmpty(x.ImageURL))
                    x.ImageURL = Commons.HostImage + "News/" + x.ImageURL;
            });
            return PartialView("_ListData", model);
        }

        public ActionResult Create()
        {
            CMS_NewsModels model = new CMS_NewsModels();
            return PartialView("_Create", model);
        }

        public CMS_NewsModels GetDetail(string Id)
        {
            var model = _factory.GetDetail(Id);
            //if (model != null)
            //    model.ImageURL = Commons.HostImage + "News/" + model.ImageURL;
            return model;
        }

        [HttpPost]
        public ActionResult Create(CMS_NewsModels model)
        {
            try
            {
                byte[] photoByte = null;
                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Create", model);
                }
                if (model.PictureUpload != null && model.PictureUpload.ContentLength > 0)
                {
                    Byte[] imgByte = new Byte[model.PictureUpload.ContentLength];
                    model.PictureUpload.InputStream.Read(imgByte, 0, model.PictureUpload.ContentLength);
                    model.PictureByte = imgByte;
                    model.ImageURL = Guid.NewGuid() + Path.GetExtension(model.PictureUpload.FileName);
                    model.PictureUpload = null;
                    photoByte = imgByte;
                }
                var msg = "";
                var result = _factory.CreateOrUpdate(model, ref msg);
                if (result)
                {
                    if (!string.IsNullOrEmpty(model.ImageURL) && model.PictureByte != null)
                    {
                        var path = Server.MapPath("~/Uploads/News/" + model.ImageURL);
                        MemoryStream ms = new MemoryStream(photoByte, 0, photoByte.Length);
                        ms.Write(photoByte, 0, photoByte.Length);
                        System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);

                        ImageHelper.Me.SaveCroppedImage(imageTmp, path, model.ImageURL, ref photoByte,400,Commons.WidthImageNews,Commons.HeightImageNews);
                    }
                    return RedirectToAction("Index");
                }
                    
                ModelState.AddModelError("Title", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Create", model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Create", model);
            }
        }

        [HttpGet]
        public ActionResult Edit(string Id)
        {
            var model = GetDetail(Id);
            if (!string.IsNullOrEmpty(model.ImageURL))
                model.ImageURL = Commons.HostImage +"News/" + model.ImageURL;
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(CMS_NewsModels model)
        {
            var temp = model.ImageURL;
            try
            {
                byte[] photoByte = null;
                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Edit", model);
                }
                if (!string.IsNullOrEmpty(model.ImageURL))
                {
                    model.ImageURL = model.ImageURL.Replace(Commons._PublicImages +"News/", "").Replace(Commons.Image272_259, "");
                }

                if (model.PictureUpload != null && model.PictureUpload.ContentLength > 0)
                {
                    Byte[] imgByte = new Byte[model.PictureUpload.ContentLength];
                    model.PictureUpload.InputStream.Read(imgByte, 0, model.PictureUpload.ContentLength);
                    model.PictureByte = imgByte;
                    model.ImageURL = Guid.NewGuid() + Path.GetExtension(model.PictureUpload.FileName);
                    model.PictureUpload = null;
                    photoByte = imgByte;
                }
                var msg = "";
                var result = _factory.CreateOrUpdate(model, ref msg);
                if (result)
                {
                    if (!string.IsNullOrEmpty(model.ImageURL) && model.PictureByte != null)
                    {
                        if (!string.IsNullOrEmpty(temp))
                        {
                            temp = temp.Replace(Commons._PublicImages + "News/", "").Replace(Commons.Image272_259, "");
                            temp = "~/Uploads/News/" + temp;
                            if (System.IO.File.Exists(Server.MapPath(temp)))
                            {
                                ImageHelper.Me.TryDeleteImageUpdated(Server.MapPath(temp));
                            }
                        }
                        var path = Server.MapPath("~/Uploads/News/" + model.ImageURL);
                        MemoryStream ms = new MemoryStream(photoByte, 0, photoByte.Length);
                        ms.Write(photoByte, 0, photoByte.Length);
                        System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);

                        ImageHelper.Me.SaveCroppedImage(imageTmp, path, model.ImageURL, ref photoByte, 400, Commons.WidthImageNews, Commons.HeightImageNews);
                    }
                    return RedirectToAction("Index");
                }
                    
                ModelState.AddModelError("Title", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Edit", model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Edit", model);
            }
        }

        [HttpGet]
        public ActionResult View(string Id)
        {
            var model = GetDetail(Id);
            if (!string.IsNullOrEmpty(model.ImageURL))
                model.ImageURL = Commons.HostImage + "News/" + model.ImageURL;
            return PartialView("_View", model);
        }

        [HttpGet]
        public ActionResult Delete(string Id)
        {
            var model = GetDetail(Id);
            return PartialView("_Delete", model);
        }

        [HttpPost]
        public ActionResult Delete(CMS_NewsModels model)
        {
            try
            {
                //if (!ModelState.IsValid)
                //{
                //    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                //    return PartialView("_Delete", model);
                //}
                var msg = "";
                var result = _factory.Delete(model.Id, ref msg);
                if (result)
                    return RedirectToAction("Index");
                ModelState.AddModelError("Title", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Delete", model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Delete", model);
            }
        }
    }
}

CMS-Web/Areas/Admin/Controllers/CMSPolicyController.cs
using CMS_DTO.CMSPolicy;
using CMS_Shared.CMSPolicy;
using CMS_Web.Web.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CMS_Web.Areas.Admin.Controllers
{
    [NuAuth]
    public class CMSPolicyController : Controller
    {
        private CMSPolicyFactory _factory;
        public CMSPolicyController()
        {
            _factory = new CMSPolicyFactory();
        }
        // GET: Admin/CMSCategories
        public ActionResult Index()
        {
            var model = new CMS_PolicyModels();
            var data = _factory.GetData();
            if (data != null)
                model = data;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CMS_PolicyModels model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return View("Index", model);
                }
                var msg = "";
                var result = _factory.InsertOrUpdate(model, ref msg);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                    
                ModelState.AddModelError("Description", msg);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View("Index", model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View("Index", model);
            }
        }
    }
}

CMS-Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link rel="shortcut icon" href="@Url.Content("~/logo.ico")" type="image/x-icon">
    <title>CMS - @ViewBag.Title</title>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Libraries/plugins/font-awesome/css/font-awesome.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/simple-line-icons/simple-line-icons.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/bootstrap/css/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/uniform/css/uniform.default.css")" rel="stylesheet" />
    @*<link href="@Url.Content("~/Libraries/plugins/bootstrap-switch/css/bootstrap-switch.min.css")" rel="stylesheet" />*@
    <!-- END GLOBAL MANDATORY STYLES -->
    <link href="@Url.Content("~/Libraries/plugins/datatables/datatables.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css")" rel="stylesheet" />
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="@Url.Content("~/Libraries/plugins/moment/moment.min.js")"></script>
    <link href="@Url.Content("~/Libraries/plugins/bootstrap-daterangepicker/daterangepicker.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/morris/morris.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/fullcalendar/fullcalendar.min.css")" rel="stylesheet" />
    @*<link href="@Url.Content("~/Libraries/plugins/jqvmap/jqvmap/jqvmap.css")" rel="stylesheet" />*@
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="@Url.Content("~/Libraries/css/components.min.css")" rel="stylesheet" id="style_components" type="text/css" />
    <link href="@Url.Content("~/Libraries/css/plugins.min.css")" rel="stylesheet" />
    <!-- END THEME GLOBAL STYLES -->

    <link href="@Url.Content("~/Libraries/plugins/icheck/skins/all.css")" rel="stylesheet" />

    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="@Url.Content("~/Libraries/layouts/layout/css/layout.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/layouts/layout/css/themes/darkblue.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/layouts/layout/css/custom.min.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Libraries/plugins/select2/dist/css/select2.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Libraries/plugins/bootstrap-select/css/bootstrap-select.min.css")" rel="stylesheet" />
   
    <!-- END THEME LAYOUT STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
    <script src="@Url.Content("~/Libraries/plugins/jquery.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/bootstrap/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Libraries/scripts/datatable.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/datatables/datatables.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")"></script>

    <script src="@Url.Content("~/Libraries/plugins/icheck/icheck.min.js")"></script>
    <script src="@Url.Content("~/Libraries/pages/scripts/form-icheck.min.js")"></script>
    <link href="@Url.Content("~/Content/Common.css")" rel="stylesheet" />
</head>
<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
    @Html.Partial("_topMenu")

    <!-- BEGIN HEADER & CONTENT DIVIDER -->
    <div class="clearfix"> </div>
    <!-- END HEADER & CONTENT DIVIDER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        @Html.Partial("_leftMenu")
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                <!-- BEGIN PAGE HEADER-->


                <!-- END PAGE HEADER-->
                @RenderBody()
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
        <!-- BEGIN QUICK SIDEBAR -->
        <a href="javascript:;" class="page-quick-sidebar-toggler">
            <i class="icon-login"></i>
        </a>
        
        <!-- END QUICK SIDEBAR -->
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    @Html.Partial("_footer")
    <!-- BEGIN CORE PLUGINS -->
    
    
    @*<script src="@Url.Content("~/Libraries/plugins/js.cookie.min.js")"></script>*@
    <script src="@Url.Content("~/Libraries/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/jquery-slimscroll/jquery.slimscroll.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/jquery.blockui.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/uniform/jquery.uniform.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/bootstrap-switch/js/bootstrap-switch.min.js")"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="@Url.Content("~/Libraries/plugins/moment.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/bootstrap-daterangepicker/daterangepicker.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/morris/morris.min.js")"></script>
    @*<script src="@Url.Content("~/Libraries/plugins/morris/raphael-min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/counterup/jquery.waypoints.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/counterup/jquery.counterup.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/amcharts.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/serial.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/pie.js")"></script>*@
    @*<script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/radar.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/themes/light.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/themes/patterns.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amcharts/themes/chalk.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/ammap/ammap.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/ammap/maps/js/worldLow.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/amcharts/amstockcharts/amstock.js")"></script>*@
    <script src="@Url.Content("~/Libraries/plugins/fullcalendar/fullcalendar.min.js")"></script>
    @*<script src="@Url.Content("~/Libraries/plugins/flot/jquery.flot.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/flot/jquery.flot.resize.min.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/flot/jquery.flot.categories.min.js")"></script>*@
   @* <script src="@Url.Content("~/Libraries/plugins/jquery-easypiechart/jquery.easypiechart.min.js")"></script>*@
    @*<script src="@Url.Content("~/Libraries/plugins/jquery.sparkline.min.js")"></script>*@
    <!-- END PAGE LEVEL PLUGINS -->
   
    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="@Url.Content("~/Libraries/scripts/app.min.js")"></script>
    <!-- END THEME GLOBAL SCRIPTS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    @*<script src="@Url.Content("~/Libraries/pages/scripts/dashboard.min.js")"></script>*@
    <!-- END PAGE LEVEL SCRIPTS -->


    <script src="@Url.Content("~/Libraries/plugins/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("~/Libraries/plugins/ckeditor/adapters/jquery.js")"></script>

    <!--Select 2-->
    <script src="@Url.Content("~/Libraries/plugins/select2/dist/js/select2.full.js")"></script>

    <script src="@Url.Content("~/Libraries/plugins/bootstrap-select/js/bootstrap-select.min.js")"></script>
    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    <script src="@Url.Content("~/Libraries/layouts/layout/scripts/layout.min.js")"></script>
    <script src="@Url.Content("~/Libraries/layouts/layout/scripts/demo.min.js")"></script>
    <script src="@Url.Content("~/Libraries/layouts/global/scripts/quick-sidebar.min.js")"></script>
    <!-- END THEME LAYOUT SCRIPTS -->
    <script src="@Url.Content("~/Scripts/Common.js")"></script>
   @* <script src="@Url.Content("~/Scripts/custom.js")"></script>*@
</body>
</html>

<script type="text/javascript">
    var CURRENT_URL = window.location.href.split('?')[0],
        $BODY = $('body'),
        $MENU_TOGGLE = $('#menu_toggle'),
        $SIDEBAR_MENU = $('#sidebar-menu');
        

    $(document).ready(function () {

        $SIDEBAR_MENU.find('li').removeClass("active");

        $SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent('li').addClass('current-page');

        $SIDEBAR_MENU.find('a').filter(function () {
            return this.href.toLowerCase() == CURRENT_URL.toLowerCase();
        }).parent('li').addClass('current-page').addClass("active");
    })
</script>

CMS-Web/Areas/Admin/Views/Shared/_breadcrumb.cshtml
@{
    Layout = null;
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="javascript:void(0)">@Model["A"]</a>
            <i class="fa fa-circle"></i>
        </li>
        <li class="active">
            <span>@Model["B"]</span>
        </li>
    </ul>
    @*<div class="page-toolbar">
        <div id="dashboard-report-range" class="pull-right tooltips btn btn-sm" data-container="body" data-placement="bottom" data-original-title="Change dashboard date range">
            <i class="icon-calendar"></i>&nbsp;
            <span class="thin uppercase hidden-xs"></span>&nbsp;
            <i class="fa fa-angle-down"></i>
        </div>
    </div>*@
</div>

CMS-Web/Areas/Admin/Views/Shared/_footer.cshtml
@{
    Layout = null;
}
<style type="text/css">
    .page-footer-inner{
        float:right !important;
    }
</style>
<div class="page-footer">
    <div class="page-footer-inner">
        2017 - @DateTime.Now.Year &copy; David Tuấn.
        <a href="javascript:void(0)">voquoctuanqn@gmail.com</a>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

CMS-Web/Areas/Admin/Views/Shared/_leftMenu.cshtml
@{
    Layout = null;
}

<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse" id="sidebar-menu">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu  page-header-fixed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
            <li class="sidebar-toggler-wrapper hide">
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler"> </div>
                <!-- END SIDEBAR TOGGLER BUTTON -->
            </li>
            <li class="nav-item active">
                <a href="@Url.Action("Index","Home")" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Trang Chủ</span>
                </a>
            </li>
            <li class="nav-item active">
                <a href="@Url.Action("Index","CMSCategories")" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Thể Loại</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("Index","CMSProducts")" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Sản Phẩm</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("Index","CMSEmployees")" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Nhân Viên</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Khách Hàng</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("Index","CMSPolicy")" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Chính Sách</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("Index","CMSNews")" class="nav-link nav-toggle">
                    <i class="fa fa-dot-circle-o"></i>
                    <span class="title">Tin Tức</span>
                </a>
            </li>  
</ul>
        <!-- END SIDEBAR MENU -->
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->